# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87d70d55c8998faa124e823787ca8fb8137ad168ac138ef5c1269b2c96aeba7ad56de4f4437466269f318ad1eaf153696adc66941eefa3ce78ff4dd82c635dfc

test:
  secret_key_base: 79e37f1f58fb767f766da7287937d4e56f3c125e899609a8c8debc6619071aac66ca34f03c5ef4d5d0dda9f9a7855d1af64d2923b2ff45e6af976d2a9acec20c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
